version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: photostore_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: photostore
      MYSQL_USER: photostore_user
      MYSQL_PASSWORD: photostore_pass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - photostore_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer - Database Management Tool
  adminer:
    image: adminer:latest
    container_name: photostore_adminer
    ports:
      - "8081:8080"
    networks:
      - photostore_network
    depends_on:
      - mysql

  # Keycloak - Identity and Access Management
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: photostore_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak?createDatabaseIfNotExist=true
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: rootpassword
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    networks:
      - photostore_network
    depends_on:
      mysql:
        condition: service_healthy
    command:
      - start-dev

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photostore_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - ./uploads:/app/uploads  # Mount local uploads directory
    networks:
      - photostore_network
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started
    restart: unless-stopped

networks:
  photostore_network:
    driver: bridge

volumes:
  mysql_data:
